### ISSUE TITLE
extract urls incorrectly in utf8 file containing non-ascii characters

### ISSUE THREAD

**Issue by youkpter** [borgified/url_checker#10]
url_checker uses URI::Find::UTF8 module to exract urls, but forget to specify utf8 encoding for input file. This will produce some wrong result. see https://github.com/EbookFoundation/free-programming-books/issues/3233#issuecomment-560128310

**Comment by borgified** [comment]
whoops! sorry for the late reply. thanks for the note and for figuring out why it was broken. i will fix the url checker script if we do end up going back to use it. right now this script is deprecated in favor of another script that also checks urls: https://github.com/EbookFoundation/free-programming-books/blob/master/.github/workflows/main.yml#L15

more info here: https://github.com/dkhamsing/awesome_bot
